email_verify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("email_verify_app.urls",namespace="user"))
    
]

email_verify_app/urls.py
from django.urls import path
from email_verify_app.views import home,register_view, token_send_view, verify,error_view, login_view

app_name= "user"
urlpatterns = [
    path("",home,name="home"),
    path("login/",login_view,name="login"),
    path("register/",register_view,name="register"),
    path("token-send/",token_send_view,name="token_send"),
    path("verify/<auth_token>/",verify,name="verify"),
    path("error",error_view,name="error"),
]

email_verify_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,UserManager

class User(AbstractUser):
    objects = UserManager()
    email = models.EmailField(("email address"), blank=False)
    
    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=200)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user.username

email_verify_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class CustomerRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields= ("username","email","password1","password2")

    

email_verify_app/views.py
from django.shortcuts import render,redirect
from email_verify_app.forms import CustomerRegisterForm
from django.contrib.auth import get_user_model
from django.contrib import messages
from email_verify_app.models import Profile
from django.forms import forms
import uuid
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required



User = get_user_model()
@login_required
def home(request):
    return render(request,"home.html")


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        user_pass = request.POST.get("password")
        
        user_obj = User.objects.filter(username = username).first()
        print(user_obj)
        if user_obj is None:
            messages.error(request,"Invalid user")
            return redirect("user:login")
        
        
        profile_obj = Profile.objects.filter(user=user_obj).first()
        
        if not profile_obj.is_verified:
            messages.error(request,"Your account is not verified so check your mail.")
            return redirect("user:login")
        
        valid_user = authenticate(username = username, password = user_pass)
        if valid_user is None:
            messages.error(request,"Invalid email or password")
            return redirect("user:login")
        login(request,valid_user)
        return redirect("user:home")
    return render(request,"login.html")
    






    

# def CustomRegisterView(CreateView):
#     model = User
#     form_class = UserRegisterForm
#     template_name = "register.html"
#     success_url = reverse_lazy("email_user_app:login")
    
    
def register_view(request):

    if request.method == "POST":
        print("POST")
        user_name = request.POST.get("username")
        user_email = request.POST.get("email")
        print(user_name)

        try:       
            form  = CustomerRegisterForm(request.POST)

            if form.is_valid():
                
                user_obj = form.save()
            
            # user_obj = User.objects.get(user_name)   
            print(user_obj) 
            auth_token = str(uuid.uuid4())
            profile_obj = Profile.objects.create(user=user_obj,auth_token=auth_token)
            profile_obj.save()
            send_main_after_registration(user_email,auth_token)
            messages.success(request,"User is registered")
            return redirect("user:token_send")
            
                
        except Exception as e:
            print(e)    
            
    else:
        form = CustomerRegisterForm()
        
    return render(request,"register.html",{"form":form})
         
         
def token_send_view(request):
    return render(request,"token_send.html")         

def send_main_after_registration(email, token):
    subject = "Your account need to be verified"
    message =f"Hi, visit the link to verify your account, http://127.0.0.1:8000/verify/{token}"
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject,message,email_from,recipient_list)
    

def verify(request,auth_token):
    try:
        profile_obj = Profile.objects.filter(auth_token = auth_token).first()
        if profile_obj:
            if profile_obj.is_verified:
                messages.success(request,"Email has been already verified")
                return redirect("user:login")
                
            profile_obj.is_verified = True
            profile_obj.save()
            messages.success(request,"Email has been verified")
            return redirect("user:login")
        else:
            return redirect("user:error")   
    except Exception as e:
        print(e)
        return redirect("user:error")
        
        

def error_view(request):
    return render(request,"error.html")

email_verify_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Verification</title>
    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/bs.min.css' %}">
    {% endblock stylesheet %}

</head>
<body>
    {% block content %}
    {% endblock content %}
    {% block script %}
    <script src="{% static 'js/bs.min.js' %}"></script>
    {% endblock script %}
</body>
</html>

email_verify_app/templates/base_html.html
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}
<div class="container">
{% block maincontent %}
</div>
{% endblock maincontent %}
{% endblock content %}

email_verify_app/templates/error.html
{% extends 'base.html' %}
{% block content %}
<h1>Error Occurred</h1>
{% endblock content %}

email_verify_app/templates/home.html
{% extends 'base_html.html' %}
{% block maincontent %}
Hello, user
{% endblock maincontent %}

email_verify_app/templates/login.html
{% extends 'base_html.html' %}



{% block maincontent %}
<div class="d-flex align-items-center justify-content-center mt-5">
<div class="card card-shadow" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Login Page</h5>
      {% if messages %}
      {% for message in messages %}
         <span class="text-success">{{message}}</span>
      {% endfor %}
      </ul>
  
    {% endif %}
      <form method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Username</label>
          <input type="text" name="username" class="form-control" id="id_username">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" name="password" class="form-control" id="id_password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <p>Don't have an account? </p>
      <a href="{% url 'user:register' %}" class="btn btn-success">Register</a>
    </div>
  </div>
  </div>


{% endblock maincontent %}

email_verify_app/templates/navbar.html
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <li class="nav-item">
                <a class="nav-link" href="#">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Logout</a>
            </li>
        </li>
        </ul>
        
      </div>
    </div>
  </nav>

email_verify_app/templates/register.html
  {% if messages %}
  <ul>
    {% for message in messages %}
      <li>
        <span class="text-success">{{ message }}</span>
      </li>
    {% endfor %}
  </ul>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="submit">
</form>

email_verify_app/templates/token_send.html
{% extends 'base.html' %}

{% block content %}
<h2>Please check mail for successfull registration.</h2>
{% endblock content %}